language: java

jdk:
  - openjdk8
  - openjdk11

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/frontend/.gradle/wrapper/
    - $HOME/frontend/.cache/
    - $HOME/frontend/node_modules/
